version: "3.5"
services:
#
# MARIADB
#
    mariadb-glpi: 
        build: mariadb/
        image: wonderu/glpi10:10.0.16-mariadb
        restart: unless-stopped
        # volumes: 
        #  - mariadb-glpi-volume:/var/lib/mysql:rw
        environment: 
          MYSQL_DATABASE: glpi
          MYSQL_USER: glpi-user 
          MYSQL_PASSWORD: glpi-pass 
          MYSQL_RANDOM_ROOT_PASSWORD: 1 
        ports: 
          - 127.0.0.1:3306:3306
        networks: 
          - glpi-backend
#
# GLPI
#
    glpi: 
        build: apache/
        image: wonderu/glpi10:10.0.16
        restart: unless-stopped
        # volumes: 
        #  - glpi-volume-files:/var/www/html/files:rw
        #  - glpi-volume-plugins:/var/www/html/plugins:rw
        #  - glpi-volume-config:/var/www/html/config:rw
        environment: 
          GLPI_LANG: en_US
          MARIADB_HOST: mariadb-glpi
          MARIADB_PORT: 3306
          MARIADB_DATABASE: glpi
          MARIADB_USER: glpi-user
          MARIADB_PASSWORD: glpi-pass
          VERSION: "10.0.16"
          PLUGINS: "all"
        depends_on: 
          - mariadb-glpi
        ports: 
          - "127.0.0.1:8901:80"
        networks: 
          - glpi-frontend
          - glpi-backend
#
# CRON
#
    cronjob: 
        build: crond/
        image: wonderu/glpi10:10.0.16-crond
        restart: unless-stopped
        depends_on: 
          - glpi
          - mariadb-glpi
        environment: 
          MARIADB_HOST: mariadb-glpi
          MARIADB_PORT: 3306
          MARIADB_DATABASE: glpi
          MARIADB_USER: glpi-user
          MARIADB_PASSWORD: glpi-pass
        # volumes: 
        #  - glpi-volume-files:/var/www/html/files:rw
        #  - glpi-volume-plugins:/var/www/html/plugins:rw
        #  - glpi-volume-config:/var/www/html/config:rw
        networks: 
          - glpi-backend
#
# VOLUMES
#
# volumes: 
#  glpi-volume-files:
#  glpi-volume-plugins:
#  glpi-volume-config:
#  mariadb-glpi-volume: 
#
# NETWORKS
#
networks: 
  glpi-frontend: 
  glpi-backend:
